server:
  port: 7777

camunda.bpm.admin-user:
  id: demo
  password: demo

bpm:
  holidayProcessId: holiday-process
  url: http://localhost:7777
  activeTask: ${bpm.url}/engine-rest/task?processInstanceBusinessKey=
  completeTask: ${bpm.url}/engine-rest/task/$TASK_ID/complete


spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./camunda-h2-database
    username:
    password:
    driverClassName: org.h2.Driver